### ISSUE TITLE
research mogelijk RPLidar (overleg met groep rijden)

### ISSUE THREAD

**Issue by Syberboy02** [R2D2-2023/Positie-Bepaling#13]

**Comment by northernlakeNL** [comment]
Manier van werken voor hun is op korte afstand en van ons op langere afstand, we moeten uitzoeken of dit elkaar in de weg gaat zitten of niet.

**Comment by Syberboy02** [comment]
Wie bedoel je met "hun"?

**Comment by northernlakeNL** [comment]
Rijden, ik dacht dat dit duidelijk zou zijn uit de taak waar de comment aan verbonden is. Sorry!

**Comment by Syberboy02** [comment]
Hmmja, ik zie nu de Github thread lmao. Ik kreeg gewoon een mail met alleen jou text dus ik had gwn zoiets van Nani tf? XD

**Comment by northernlakeNL** [comment]
Afstand van scannen van de lidar :)
