### ISSUE TITLE
Lidar capture image

### ISSUE THREAD

**Issue by Ilias-a** [R2D2-2023/Positie-Bepaling#27]
Met de lidar een live image capture dat gebruikt kan worden voor image matching.

D.O.D:
- live image capture
- Image zit er vergelijkbaar uit met de map van team mapping

**Comment by northernlakeNL** [comment]
@Boehmer2003 @Tjees @Ilias-a hebben de lidar image opnieuwe gecaptured waardoor wij betere matches kunnen krijgen voor de map en positiebepaling op de grid.
