### ISSUE TITLE
Gyro kompas(N,Z,W,O) maken

### ISSUE THREAD

**Issue by Ilias-a** [R2D2-2023/Positie-Bepaling#28]
De graden van de gyro omzetten in een kompas.

D.O.D:
-Graden zijn omgezet in alle 4 hoofd richtingen(Noord, Zuid, West en Oost)

**Comment by northernlakeNL** [comment]
@Tjees heeft een compas gemaakt van de MPU6050, dit heeft @DvnGBulletZz geimplementeerd bij mobiel platform.
