### ISSUE TITLE
Data verzenden Pi -> Arduino

### ISSUE THREAD

**Issue by Ilias-a** [R2D2-2023/Positie-Bepaling#29]
Data kunnen verzenden van een Pi naar Arduino

D.O.D:
-Boolean kunnen sturen
-String kunnen verzenden (x en y coordinaten)
-Integer kunnen verzenden voor de switchcase

**Comment by northernlakeNL** [comment]
tjez heeft data weten te verzenden van de pi naar de arduino en terug
