### ISSUE TITLE
Lidar image matching

### ISSUE THREAD

**Issue by Ilias-a** [R2D2-2023/Positie-Bepaling#30]
Image generated from live lidar data, has to match with its positions on the the map image.

D.O.D:
-Make a square border for the purpose of matching
-Match generated live image against the map image
-Matching has to closely match actual position

**Comment by northernlakeNL** [comment]
@Boehmer2003 @Tjees @Ilias-a hebben een nieuwe map gemaakt waardoor er nog betere matches komen op de map die worden overgeheveld naar de mapping map om de positie te bepalen.
