### ISSUE TITLE
Map draaien met gyro kompas

### ISSUE THREAD

**Issue by Ilias-a** [R2D2-2023/Positie-Bepaling#31]
Map has to rotate according to the North, West, South, East direction indicated by the gyro.

D.O.D:
-Add code for map rotation
-Rotate the map according to the input given by the gyro

**Comment by northernlakeNL** [comment]
@Boehmer2003 @Ilias-a en @Tjees hebben dit gemaakt en getest op werking met de proef auto van mapping.
